version: '3'
services:
  service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    restart: unless-stopped
  pgadmin:
    depends_on:
      - service-db
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
  app:
    depends_on:
      - service-db
      - pgadmin
    ports:
      - "6868:8080"
    build: .
