spring:
  application:
    name: becoder-api
  datasource:
    #url: jdbc:postgresql://localhost:5432/becoder
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate: INFO
      hibernate.SQL: DEBUG
      hibernate.cache: DEBUG
      hibernate.stat: DEBUG
jwt:
  secret: 3RH7aHFDcWmpvtvAUhssAPSWheh87wWtu52HQvdlkDch7JkGrnKVsh9FJknroEC2
  exp: 10080
server:
  port: 6868